arkanoidConfig = {
    "PADDLE_WIDTH": 100,
    "PADDLE_HEIGHT":  20,
    "BRICK_WIDTH": 80,
    "BRICK_HEIGHT": 50,
    "BRICK_OFFSET_Y": 45,
    "BRICK_OFFSET_X": 10,
    "PADDLE_COLOR": "#4B4B4B",
    "CANVAS_WIDTH": 800,
    "CANVAS_HEIGHT": 600,
    "OFFSET_X": 30,
    "OFFSET_Y":  5,
    "PADDLE_SPEED": [8, 3],
    "BALL_RADIUS": 15,
    "BALL_HP": 5,
    "BONUS_RADIUS": 12,
    "FALLING_SPEED": 0.05,
    "BALL_MAX_SPEED": 6,
    "FRICTION": 0.1,
    "BALL_DAMAGE": 10,
    "LIVES": 3,
    "PADDLE_ZONE": 150,
    "FRAMES_RATE": 60
}